### ISSUE TITLE
CVE IDs are only referenced and not contained

### ISSUE THREAD

**Issue by FloBoJa** [FluidTrust/Palladio-Addons-ContextConfidentiality-Metamodel#8]
CVEIDs are not contained in their respective vulnerability. This has the consequence that they have to be added to a resource manually, which does not seem to make much sense.

The code used:

```java
Vulnerability vuln = ...;
CVEID cveId = ...;
vuln.setCveId(cveid);
```

The expected result:

```xmi
<attack:CVEVulnerability entityName="CVE-2021-43859" attackVector="Network" availabilityImpact="High">
    <attack:CVEID entityName="CVE-2021-43859" cveID="CVE-2021-43859"/>
</attack:CVEVulnerability>
```

The result after adding the object to the resource manually;

```xmi
<attack:CVEVulnerability entityName="CVE-2021-43859" attackVector="Network" availabilityImpact="High" cveID="/1"/>
<attack:CVEID entityName="CVE-2021-43859" cveID="CVE-2021-43859"/>
```

**Comment by majuwa** [comment]
The idea is to have them separated, because they are reused for the attack definition. [This](https://github.com/FluidTrust/Palladio-Addons-ContextConfidentiality-Analysis/blob/e12ab57a49b10b9f9badd35273c5f6460a8c518b/tests/org.palladiosimulator.pcm.confidentiality.context.analysis.testmodels/models/powerGrid/My.attacker) example shows the usage for attacks. It references the CVEID.
Additionally, there are some cases, where I want to reuse the CVE-ID as more general concept for a vulnerability. There could be different different vulnerability instances of the same CVEID. For instance, if the same component is multiple time instantiated some properties of the Vulnerability class might be different such as the credentials or even the impact description. Therefore, I chose to not contain them, but only to reference them.
